collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.781362
  brandStrength: 0.4354839
  lightness: 0.5143369
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#646464'
    - '#CACACA'
    - '#999999'
  rhythmicContrast: 0.453405
typography_spectrum: 0.5197133
layout_spectrum: 0.9551972
name: YaDiGGiT
