collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6129032
  brandStrength: 0.4354839
  lightness: 0.6164874
  brandColors:
    - '#010000'
    - '#FFFFFF'
    - '#A6A8A7'
    - '#4B494A'
    - '#898788'
  rhythmicContrast: 0.453405
typography_spectrum: 0.9390681
layout_spectrum: 0.9014337
name: YaDiGGiT
